# Generated by Django 5.0.7 on 2025-09-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0005_resume_file_resume_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='credential_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certification',
            name='issuer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='certification',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
