# Generated by Django 5.0.7 on 2025-09-14 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0007_alter_project_tech_stack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
