# Generated by Django 5.0.7 on 2025-09-14 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0010_experience_created_at_experience_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='is_current',
        ),
    ]
