# Generated by Django 5.0.7 on 2025-09-14 15:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0011_remove_experience_is_current'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(default='Unknown Company', max_length=255),
        ),
        migrations.AlterField(
            model_name='experience',
            name='role',
            field=models.CharField(default='Unknown Role', max_length=255),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='experience',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
